### ISSUE TITLE
Chat of some sorts?

### ISSUE THREAD

**Issue by nitori** [traverseda/PyCraft#11]
Do you think we could open up some sort of chat, that makes communication a bit easier?

The two places I'm in anyway:
- IRC (e.g. Freenode)
- Slack ([devolio-devchat.slack.com](https://devolio-devchat.slack.com/))

**Comment by traverseda** [comment]
I'm "traverseda" on freenode.

I'll also hang out on #pycraft on freenode. I suppose I may as well get it properly registered and stuff, but that will have to wait until tomorrow.

I'll add it to the README once that's set up.

**Comment by nitori** [comment]
Great, I joined. I guess this issue can be closed then :-)
