### ISSUE TITLE
Add a gitter room for this project

### ISSUE THREAD

**Issue by mrpudn** [traverseda/PyCraft#15]
It might be nice to have a [gitter](https://gitter.im) room to help facilitate discussion beyond issues / pull requests. Thoughts?

**Comment by nitori** [comment]
We already decided in #11 for a simple IRC room on Freenode.

**Comment by traverseda** [comment]
I've added it to the readme.

**Comment by traverseda** [comment]
But yeah, idle on #pycraft on freenode.
