### ISSUE TITLE
Backfill unit tests

### ISSUE THREAD

**Issue by mrpudn** [traverseda/PyCraft#17]
Just thought I'd add this in here, as I'm currently working on it.

Having at least some of the more essential functionality unit tested will help immensely when we start adding more complexity.

There's still quite a lot of decoupling yet to be done that might go along with this.

**Comment by traverseda** [comment]
I don't know if anything's going to graduate to "essential" for a while, but good to have it out there.

**Comment by mrpudn** [comment]
Yeah, I expect a lot of things to change, but it'd be nice to get a Travis CI build going and start encouraging some good practices :)

**Comment by mrpudn** [comment]
I think I'll close this one for now and we'll just aim for higher coverage once #29 goes through
