### ISSUE TITLE
Show current block

### ISSUE THREAD

**Issue by mrpudn** [traverseda/PyCraft#18]
Should the currently selected block be displayed on the screen (perhaps the bottom left corner)?

**Comment by traverseda** [comment]
Not a bad idea, maybe isometric if it isn't too hard.

In the longer term, we want something a bit more generic. But it'll do.

**Comment by mrpudn** [comment]
Yup, I was thinking we could mark this as "help wanted" so that others could get involved - thoughts?

**Comment by traverseda** [comment]
Looks like a good introduction.

**Comment by brianbruggeman** [comment]
This is likely best done with a ray casting algorithm.

**Comment by johndikeman** [comment]
seems like PR #44 should have closed this issue?
