### ISSUE TITLE
"Object oriented" API for implementing new block types.

### ISSUE THREAD

**Issue by traverseda** [traverseda/PyCraft#2]
It should be pretty simple to create new blocks. Just define a new block, inheriting from "objects.base.block".

Off the top of my head, a few methods objects.base.block should implement.

```
delete() #Called when an object gets deleted
texture() #Called when the engine tries to draw a block. You can implement animated textures with it.
interact() #Called when a user tries to interact with an object
location() #returns the current blocks location.
uuid() #The unique ID of a block, if it should have one. This is for objects like chests.
```

Some of those should probably be attributes, then wen can make the properties.

---

Longer term, instantiating hundred of thousands of blocks is probably a bad plan.

**Comment by traverseda** [comment]
- [X] We're also going to need a system for loading in objects.

**Comment by traverseda** [comment]
https://github.com/diffoperator/pycow Might be a relatively painless solution to our massive object duplication _thing_.

A chest is a generic chest, until you write to it. Grass is probably always generic grass, unless you instantiate it with some biome specific stuff or something.

What I'd really like is CoW classes along with some kind of deduplicaition, but that's a bit much to expect.

**Comment by ocarneiro** [comment]
I've started a similar project some time ago (https://github.com/ocarneiro/mine.py) and bumped into the separation between the pyglet implementation of showing the blocks and the model itself. 

My approach was to make a separate World object that can be drawn in text mode. 

Please take a look at my repo and take anything you find useful. I'll check in here often to see how I can help.

Congratulations on your effort!

**Comment by traverseda** [comment]
Yeah, I saw that. I suspect I'll be pulling a lot out of that. The only reason I haven't merged it straight in is because I already started on some object oriented block stuff.

@TristanTrim, this might be relevant to your interests, especially the text mode stuff.

**Comment by traverseda** [comment]
```

class StonePickaxe(Tool):
    durability = 1000
    recipe = [
        [Stone, Stone, Stone],
        [None, Stick, None],
        [None, Stick, None],
    ]

    def hit(self, block):

```

edric_garran [on reddit](https://www.reddit.com/r/Python/comments/4f9jqo/remember_minecraft_in_500_lines_of_python_were/d27gi0j)
