### ISSUE TITLE
Graphics settings file

### ISSUE THREAD

**Issue by traverseda** [traverseda/PyCraft#25]
Probably yaml.

**Comment by mrpudn** [comment]
Would this be for like shaders, textures, default resolution, etc?

**Comment by traverseda** [comment]
More things that affect performance. Whether or not shaders are enabled and draw distance being the two main ones.

Also probably frame rate.

I say this from a shitty arm chromebook running hacked-in linux.

**Comment by traverseda** [comment]
#36 covers some of this. Decided to make a bit more generic of a solution, that we can grow with.

**Comment by marquesVF** [comment]
I'm working in a possible solution for this issue using a JSON file that would be stored in the HOME directory. This configuration file would be created on the fly at the first time the game would be initialized with default values.

**Comment by traverseda** [comment]
I can't complain about that. Part of why the current settings is a python file is so that we could implement that kind of solution later.

But since I'm not merging in my own PR's, that might be the only way to get it in ;p

**Comment by traverseda** [comment]
#43 solves this.

**Comment by fuzzy-focus** [comment]
couple of parameters that should also be included:
- zFar for gluPerspective in Window.set_3d() (currently 60, ran without problem even with 200 for me)
- values for GL_FOG_START and GL_FOG_END (in World.init_gl_fog())

Might issue a pull request when I'm home.
