### ISSUE TITLE
Travis CI and coveralls

### ISSUE THREAD

**Issue by mrpudn** [traverseda/PyCraft#29]
Pending PR #28 (and #17) - we'll have some (meager) unit tests and instructions for running them. With that, it'd be nice to have some [Travis CI](https://travis-ci.org/) and [Coveralls](https://coveralls.io/) integration, along with a helpful badge in the readme for each.

**Comment by ghevcoul** [comment]
I can start trying to get the travis.yml file working for when we have unit tests merged.

**Comment by ghevcoul** [comment]
Not sure why the coverage badge in the README is showing as unknown, Coveralls is definitely properly on the PRs. I've double checked the embed code shown on their website and it's definitely exactly what they give.

**Comment by traverseda** [comment]
Who can say. I'll leave this open for now, until it's up and running.

**Comment by mrpudn** [comment]
@ghevcoul Yeah, I've noticed that on other projects, but it should start working after a day or so
