### ISSUE TITLE
Terrible performance

### ISSUE THREAD

**Issue by gholaday** [traverseda/PyCraft#30]
Not sure why but when I run pycraft i can barely move the cursor and the game freezes every second or so. 

On windows 10 if that matters.

Any ideas?

**Comment by kinow** [comment]
Probably providing more information about your hardware and software environment may help. Like specific OS (look for the screen about Windows, copy everything like 64 or 32 bits, Windows SP version, etc), and also your hardware (number of cores, amount of memory, etc). The more information, the more likely that one developer of the project will pick your issue to investigate that.

**Comment by mrpudn** [comment]
Besides a slightly buggy startup, it works fine for me (on Mac).

@traverseda is working on #25, so after that's done you might be able to pin down the problem by switching things off.
