### ISSUE TITLE
normalize

### ISSUE THREAD

**Issue by 4rokis** [traverseda/PyCraft#59]
Is this method correct? One give it tuple of 3 floats ant it round it and return as int? Round if i am correct means 5.4 = 5 and 5.5=6 and 5.8=6. Is that correct? If yes i am repairing that test
`def normalize(position):
    x, y, z = position
    x, y, z = (int(round(x)), int(round(y)), int(round(z)))
    return x, y, z`

**Comment by traverseda** [comment]
If anyone is googling this error, it's because we only support python > 3.4
