### ISSUE TITLE
test_licences failing

### ISSUE THREAD

**Issue by 4rokis** [traverseda/PyCraft#61]
Licences printed by test ( little change to the test about not failing right away but test all of them and fails after, preparing PR). 
!!!(failed, licence not found or not accepted) NAME_OF_MODULE : LICENCE

I am looking for help about individual licences, check if they are OK and each module with licence UNKNOWN need to be checked manually. Put everything in comments

  matplotlib:BSD
    PyYAML: MIT
    numpy: BSD
    MarkupSafe: BSD
    pwquality: BSD or GPLv2+
    Jinja2: BSD
!!! python-dmidecode: GPL-2
!!! lxml: UNKNOWN
!!! sepolicy: UNKNOWN
!!! python-systemd: LGPLv2+
!!! Brlapi: LGPL 2.1
!!! pycups: GPLv2+
!!! Pillow: Standard PIL License
!!! rpm-python: UNKNOWN
!!! pyparted: GPLv2+
!!! pygobject: GNU LGPL
!!! PyIscsi: UNKNOWN
!!! pygpgme: LGPL
!!! sosreport: GPLv2+
!!! openshot-qt: GNU GPL v.3
!!! devassistant: GPLv2+
!!! langtable: GPLv3+
!!! pid: ASL
!!! blivet: UNKNOWN
!!! python-augeas: UNKNOWN
    javapackages: BSD
    pytz: MIT
    pyinotify: MIT License
    urllib3: MIT
    pyglet: BSD
    requests-file: Apache 2.0
    ntplib: MIT
    requests-ftp: Apache 2.0
    six: MIT
    requests: Apache 2.0
    future: MIT
    cssselect: BSD
    Mako: MIT
    humanize: MIT
    decorator: BSD License
    Beaker: BSD
    python-dateutil: Simplified BSD
    httplib2: MIT
    iniparse: MIT
    IPy: BSD License
    pyparsing: MIT License
    progress: ISC
!!! setroubleshoot: GPLv3+
!!! dnf-langpacks: GPLv2+
!!! PyGithub: UNKNOWN
!!! python-meh: UNKNOWN
!!! slip.dbus: UNKNOWN
!!! cupshelpers: UNKNOWN
!!! chardet: LGPL
!!! slip: UNKNOWN
!!! seobject: GPLv2+
!!! initial-setup: GPLv2+
!!! pykickstart: UNKNOWN
!!! SSSDConfig: GPLv3+
!!! fros: GPLv2+
!!! pyxdg: UNKNOWN
!!! pyudev: LGPL 2.1+
!!! dapp: GPLv2+

**Comment by nitori** [comment]
Most of these packages are not used in this project.

See if you use the correct `py.test` script: `py.test --version`.

It Should point to your virtual environment.

**Comment by traverseda** [comment]
Did #62 fix this?

**Comment by nitori** [comment]
I think his problem is something else.

It looks more like he ran a system wide `py.test`, instead of only for the environment. I had the same issue at first.

Edit: but yea. The problem should not arise, if you only install the dependencies from the requirements files.

**Comment by 4rokis** [comment]
Sorry error was really on my side. Followed travis-ci log and found out missing steps.

create a virtual environment

virtualenv -p python3 ~/.venv/pycraft # (or wherever)
 you may need to add execute permissions
chmod -R a+x ~/.venv
activate
. ~/.venv/pycraft/bin/activate # on mac
. ~/.venv/pycraft/Scripts/activate # on windows
deactivate (when you're done)
deactivate

and 

cd ${PATHTOPYCRAFTCLONE}

source ${PATHTOACTIVATE};
pip install -r requirements.txt;
pip install -r requirements-dev.txt;
pip install coveralls;
py.test --cov=. --cov-config .coveragerc .;
