### ISSUE TITLE
What are the Intended Target platforms for pycraft?

### ISSUE THREAD

**Issue by HeadClot** [traverseda/PyCraft#81]
What are the intended target platforms for pycraft?

Are we just going to target Windows, Mac, and Linux PCs or are we going to Target smart devices powered by android and iOS as well?

Referencing #34 as this is worth talking about.

**Comment by traverseda** [comment]
Smart devices would be great. I think they're probably going to be second class citizens for a while though, unless someone takes ownership of it and provides automated testcases for building to smart-devices.

**Comment by HeadClot** [comment]
Hey @traverseda - Thanks for the reply.

I have been doing some research into getting pycraft onto smart devices.
I think that [Kivy](https://kivy.org/) would be great for android and iOS support.

It is based on OpenGLES2. The Repo for Kivy is [here](https://github.com/kivy/kivy) 

It is also MIT licensed.

**Comment by traverseda** [comment]
I'm a bit familiar with kivy.

I've got no problem letting kivy handle our input/eventloop/whatever.

I don't know how well it deals with 3D stuff, or with pyglet.
